version: 2.1
default: &default
  parameters:
    python-version:
      description: the Python version we want to test with
      type: string
      default: "3.9.6"
  docker:
    - image: cimg/python:<< parameters.python-version >>
      environment: # environment variables for primary container
        PIPENV_VENV_IN_PROJECT: true
jobs:
  test:
    <<: *default
    steps: # steps that comprise the `build` job
      - add_ssh_keys:
          fingerprints:
            - "c8:f7:fc:a0:0d:2c:43:93:e3:c7:b6:cf:16:93:98:e1"
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            make setup
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            make test
      - run:
          command: |
            make coverage
  docs-build-deploy:
    <<: *default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c8:f7:fc:a0:0d:2c:43:93:e3:c7:b6:cf:16:93:98:e1"
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            make setup
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            git config --local user.email "sysadmin@binary.com"
            git config --local user.name "gh-pages deploy bot"
            make gh-pages
  update_schema:
    <<: *default
    steps:
      - checkout
      - run:
          name: config git
          command: |
            git config --global user.email "nobody@deriv.com"
            git config --global user.name "Nobody"
      - run:
          name: update schema
          command: |
            git clone https://github.com/binary-com/deriv-developers-portal.git /tmp/deriv-developers-portal
            curl -L https://cpanmin.us | perl - --sudo App::cpanminus
            sudo cpanm -n Dir::Self File::Basename JSON::MaybeXS Log::Any Path::Tiny Template Syntax::Keyword::Try
            BINARYCOM_API_SCHEMA_PATH=/tmp/deriv-developers-portal/config/v3 perl scripts/regen-py.pl
            if [[ $(git diff --shortstat) == ' 2 files changed, 2 insertions(+), 2 deletions(-)' ]]
            then
              echo 'Schema no change'
              exit 0
            else
              echo "Schama updated"
              git add .
              git commit -m 'update schema automatically'
              git push -u origin
            fi

workflows:
  build:
    jobs:
      - test:
          matrix: &matrix
            parameters:
              python-version:
                - "3.9.6"
                - "3.9.8"
                - "3.9.9"
                - "3.9.10"
                - "3.9.11"
                - "3.9.12"
                - "3.9.13"
                - "3.9.16"
                - "3.10.0"
                - "3.10.1"
                - "3.10.2"
                - "3.10.3"
                - "3.10.4"
                - "3.10.10"
      - docs-build-deploy:
          filters:
            branches:
              only:
                - master
      - update_schema
          filters:
            branches:
              only:
                - master

         
